MIN_LENGTH = 10
UPPERCASE_REQUIRED = True
LOWERCASE_REQUIRED = True
NUMERIC_REQUIRED = True
SPECIAL_CHARACTER_REQUIRED = True
COMMON_PASSWORDS_ENABLED = True
MAX_FAILED_LOGIN_ATTEMPTS = 3
PASSWORD_HISTORY_COUNT = 3  # <= 10
