# Generated by Django 4.2.3 on 2023-08-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compuer_Security_Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
    ]
